# Gradle keeps running out of heap space
org.gradle.jvmargs=-Xmx1G

minecraft_version=1.20.5
yarn_mappings=1.20.5+build.1
loader_version=0.15.10
fabric_version=0.97.7+1.20.5

libblockattributes_version=0.15.0-pre.2
libnetworkstack_version=0.12.0-pre.2

# Compat dependencies

# WAILA/WTHIT
wthit_enabled=true
wthit_version=11.1.1
