# Gradle keeps running out of heap space
org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.7
fabric_version=0.107.0+1.21.1

libblockattributes_version=0.16.0-pre.2
libnetworkstack_version=0.13.0-pre.1

# Compat dependencies

# WAILA/WTHIT
wthit_enabled=true
wthit_version=12.2.3
